[project]
name = "blender-webstats"
version = "0.0.1"
description = "Blender addon for remotely monitoring render progress"
authors = [
    {name = "Christoph J. Scherr",email = "software@cscherr.de"}
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blender-stubs (>=3.12.27,<4.0.0)",
    "pytest (>=9.0.1,<10.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
